# Generated by Django 3.1.3 on 2020-12-01 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('case', models.CharField(max_length=120)),
                ('layout', models.CharField(max_length=5)),
                ('requireSwitchMod', models.BooleanField()),
                ('lube', models.BooleanField()),
                ('film', models.BooleanField()),
                ('notes', models.CharField(max_length=500)),
            ],
        ),
    ]
