# Generated by Django 3.1.3 on 2020-12-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customerdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('itemType', models.CharField(max_length=120)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=120)),
                ('thumbnail', models.CharField(max_length=120)),
            ],
        ),
    ]
